# Generated by Django 4.1.4 on 2023-02-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=100)),
                ('año_de_lanzamiento', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas_peliculas')),
            ],
        ),
    ]
