# Generated by Django 4.1.4 on 2023-02-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_peliculas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
