# Generated by Django 4.1.4 on 2023-02-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_peliculas_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinopsis', models.CharField(max_length=1000)),
                ('recaudacion', models.FloatField()),
                ('donde_ver', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=20)),
            ],
        ),
    ]
