# Generated by Django 4.1.4 on 2023-02-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_detallepelicula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepelicula',
            options={'verbose_name': 'pelicula', 'verbose_name_plural': 'peliculas'},
        ),
    ]
