# Generated by Django 4.1.4 on 2023-02-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_alter_detallepelicula_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peliculas',
            options={'verbose_name': 'pelicula', 'verbose_name_plural': 'peliculas'},
        ),
    ]
