# Generated by Django 4.1.4 on 2023-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_alter_peliculas_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePelicula',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='donde_ver',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='duracion',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='genero',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='recaudacion',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='sinopsis',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
