# Generated by Django 4.1.4 on 2023-02-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0009_delete_detallepelicula_peliculas_donde_ver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peliculas',
            options={'verbose_name': 'Pelicula', 'verbose_name_plural': 'Peliculas'},
        ),
    ]
