# Generated by Django 4.1.4 on 2023-02-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad_de_temporadas', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Terminada', 'Terminada')], max_length=50)),
                ('donde_ver', models.CharField(max_length=100)),
                ('sinopsis', models.CharField(max_length=1000)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas_series')),
                ('año_de_lanzamiento', models.DateField()),
                ('estado_personal', models.BooleanField(default=False)),
            ],
        ),
    ]
