# Generated by Django 4.1.4 on 2023-02-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='año_de_lanzamiento',
            field=models.IntegerField(),
        ),
    ]
